#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  AutonSelector,  sensorTouch)
#pragma config(Sensor, I2C_1,  LeftFrontTop,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  RightFrontTop,  sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           LeftFrontTop,  tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port2,           LeftFrontBottom, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LeftBackTop,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LeftBackBottom, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           RightFrontTop, tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port6,           RightFrontBottom, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RightBackTop,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RightBackBottom, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Intake,        tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
void driveForward()
{
	//left side
	motor[LeftFrontTop] = 100;
	motor[LeftFrontBottom] = 100;
	motor[LeftBackTop] = 100;
	motor[LeftBackBottom] = 100;
	//right side
	motor[RightFrontTop] = 100;
	motor[RightFrontBottom] = 100;
	motor[RightBackTop] = 100;
	motor[RightBackBottom] = 100;
}
void driveBackward()
{
	//left side
	motor[LeftFrontTop] = -100;
	motor[LeftFrontBottom] = -100;
	motor[LeftBackTop] = -100;
	motor[LeftBackBottom] = -100;
	//right side
	motor[RightFrontTop] = -100;
	motor[RightFrontBottom] = -100;
	motor[RightBackTop] = -100;
	motor[RightBackBottom] = -100;
}
void turnLeft ()
{
	//right side
	motor[RightFrontTop] = -100;
	motor[RightFrontBottom] = -100;
	motor[RightBackTop] = -100;
	motor[RightBackBottom] = -100;
	//left side
	motor[LeftFrontTop] = 100;
	motor[LeftFrontBottom] = 100;
	motor[LeftBackTop] = 100;
	motor[LeftBackBottom] = 100;
}
void turnRight () {
	//right side
	motor[RightFrontTop] = 100;
	motor[RightFrontBottom] = 100;
	motor[RightBackTop] = 100;
	motor[RightBackBottom] = 100;
	//left side
	motor[LeftFrontTop] = -100;
	motor[LeftFrontBottom] = -100;
	motor[LeftBackTop] = -100;
	motor[LeftFrontBottom] = -100;
}

void turnBackLeft () {
	//left side
	motor[LeftFrontTop] = 100;
	motor[LeftFrontBottom] = 100;
	motor[LeftBackBottom] = 100;
	motor[LeftBackTop] = 100;
	//right side
	motor[RightFrontTop] = -100;
	motor[RightFrontBottom] = -100;
	motor[RightBackBottom] = -100;
	motor[RightBackTop] = -100;
}

void turnBackRight () {
	motor[LeftFrontTop] = -100;
	motor[LeftFrontBottom] = -100;
	motor[LeftBackBottom] = -100;
	motor[LeftBackTop] = -100;
	//right side
	motor[RightFrontTop] = 100;
	motor[RightFrontBottom] = 100;
	motor[RightBackBottom] = 100;
	motor[RightBackTop] = 100;
}

void stopDrive (){
	//right side
	motor[RightFrontTop] = 0;
	motor[RightFrontBottom] = 0;
	motor[RightBackTop] = 0;
	motor[RightBackBottom] = 0;
	//left side
	motor[LeftFrontTop] = 0;
	motor[LeftFrontBottom] = 0;
	motor[LeftBackTop] = 0;
	motor[LeftBackBottom] = 0;
}

void startIntake () {
	motor[Intake] = 100;
}

void stopIntake () {
	motor[Intake] = 0;
}
void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	if (SensorValue[AutonSelector] == 0) {
		wait1Msec(1000);
		resetMotorEncoder(LeftFrontTop);
		resetMotorEncoder(RightFrontTop);
		while (getMotorEncoder(LeftFrontTop) < 1800){
			driveForward();
			startIntake();
		}
		while (getMotorEncoder(LeftFrontTop) < 720) {
			turnBackRight ();
		}
		while (getMotorEncoder(LeftFrontTop) < 720) {
			driveBackward ();
		}
	}
	else if (SensorValue[AutonSelector] == 1) {
		wait1Msec(1000);
		resetMotorEncoder(LeftFrontTop);
		resetMotorEncoder(RightFrontTop);
		while (getMotorEncoder(LeftFrontTop) < 1800) {
			driveForward();
			startIntake();
		}
		while (getMotorEncoder(LeftFrontTop) < 720){
			turnBackLeft();
		}
		while (getMotorEncoder(LeftFrontTop) < 360){
			driveBackward();
		}
	}

	else {
		stopDrive();
	}
}
	/*---------------------------------------------------------------------------*/
	/*                                                                           */
	/*                              User Control Task                            */
	/*                                                                           */
	/*  This task is used to control your robot during the user control phase of */
	/*  a VEX Competition.                                                       */
	/*                                                                           */
	/*  You must modify the code to add your own robot specific commands here.   */
	/*---------------------------------------------------------------------------*/

	task usercontrol()
	{
		// User control code here, inside the loop

		while (true)
		{
			//right side is on the joystick, on channel two
			motor[RightFrontTop] = vexRT[Ch2];
			motor[RightFrontBottom] = vexRT[Ch2];
			motor[RightBackTop] = vexRT[Ch2];
			motor[RightBackBottom] = vexRT[Ch2];
			//left side is on the joystick, on channel three
			motor[LeftFrontTop] = vexRT[Ch3];
			motor[LeftFrontBottom] = vexRT[Ch3];
			motor[LeftBackTop] = vexRT[Ch3];
			motor[LeftBackBottom] = vexRT[Ch3];
			//capflipper/intake is on the 6 Up button
			if(vexRT[Btn6U] == 1) {
				motor[Intake] = 100;
			}
			else {
				motor[Intake] = 0;
			}
		}
	}
