#pragma config(Sensor, dgtl1,  AutonSelector,  sensorTouch)
#pragma config(Sensor, I2C_1,  FrontRight,     sensorNone)
#pragma config(Sensor, I2C_2,  BackRight,      sensorNone)
#pragma config(Sensor, I2C_3,  FrontLeft,      sensorNone)
#pragma config(Sensor, I2C_4,  BackLeft,       sensorNone)
#pragma config(Motor,  port1,           FrontRightBase, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           CenterRightBase, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           BackRightBase, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FrontLeftBase, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           CenterLeftBase, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           BackLeftBase,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           Intake,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void driveForward () {
	//code to move the base forward
	motor[FrontRightBase] = 100;
	motor[BackRightBase] = 100;
	motor[CenterRightBase] = 100;
	motor[FrontLeftBase] = 100;
	motor[BackLeftBase] = 100;
	motor[CenterLeftBase] = 100;
}

void driveBackward () {
	//code to move the base backwards
	motor[FrontRightBase] = -100;
	motor[BackRightBase] = -100;
	motor[CenterRightBase] = -100;
	motor[FrontLeftBase] = -100;
	motor[BackLeftBase] = -100;
	motor[CenterLeftBase] = -100;
}

void turnLeft () {
	//code to move the base left
	motor[FrontRightBase] = -80;
	motor[BackRightBase] = -80;
	motor[CenterRightBase] = -80;
	motor[FrontLeftBase] = 80;
	motor[BackLeftBase] = 80;
	motor[CenterLeftBase] = 80;
}

void turnRight () {
	//code to move the base right
	motor[FrontRightBase] = 80;
	motor[BackRightBase] = 80;
	motor[CenterRightBase] = 80;
	motor[FrontLeftBase] = -80;
	motor[BackLeftBase] = -80;
	motor[CenterLeftBase] = -80;
}

void stopDrive () {
	//code to stop the base
	motor[FrontRightBase] = 0;
	motor[BackRightBase] = 0;
	motor[CenterRightBase] = 0;
	motor[FrontLeftBase] = 0;
	motor[BackLeftBase] = 0;
	motor[CenterLeftBase] = 0;
}

void startIntake (){
	//code to turn on the intake
	motor[Intake] = 127;
}

void stopIntake (){
	//code to turn off the intake
	motor[Intake] = 0;
}


void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.

	//slaveMotor makes sure the motors on the back side of the base follows the front side of the base.
	//For example, the back right side of the base will follow the front side fo the base.
	//In this same way, the intake left motor is "slaved" to the intake right motor




	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	if (SensorValue[AutonSelector] == 0) {
		//code for front blue square
		driveForward();
		startIntake();
		wait1Msec(1300);
		stopDrive();
		stopIntake();
		wait1Msec(200);

		motor[FrontRightBase] = 80;
		motor[BackRightBase] = 80;
		motor[CenterRightBase] = 80;
		motor[FrontLeftBase] = -90;
		motor[BackLeftBase] = -90;
		motor[CenterLeftBase] = -90;

		wait1Msec(400);
		driveBackward();

		wait1Msec(1300);
		stopDrive();
	}
	else if (SensorValue[AutonSelector] == 1) {
		//Code for front red square
		driveForward();
		startIntake();
		wait1Msec(1200);
		stopDrive();
		stopIntake();
		wait1Msec(200);
		driveBackward();
		wait1Msec(5);

		motor[FrontRightBase] = -110;
		motor[BackRightBase] = -110;
		motor[CenterRightBase] = -110;
		motor[FrontLeftBase] = 60;
		motor[BackLeftBase] = 60;
		motor[CenterLeftBase] = 60;

		wait1Msec(400);
		driveBackward();

		wait1Msec(1300);
		stopDrive();
	}
	else {
		stopDrive();
	}
}




/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{

		//motor control for the right side of base
		motor[FrontRightBase] = vexRT[Ch2];
		motor[BackRightBase] = vexRT[Ch2];
		motor[CenterRightBase] = vexRT[Ch2];

		//motor control for the left side of base
		motor[FrontLeftBase] = vexRT[Ch3];
		motor[BackLeftBase] = vexRT[Ch3];
		motor[CenterLeftBase] = vexRT[Ch3];
		//motor control for the intake/cap flipper
		if (vexRT[Btn6U]) {
			motor[Intake] = 100;
		}
		else {
			motor[Intake] = 0;
		}
	}
}
