#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           FrontLeftBase, tmotorVex393_HBridge, openLoop, reversed, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port2,           CenterLeftBase, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           BackLeftBase,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FrontRightBase, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           CenterRightBase, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           CapFlipper,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          BackRightBase, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void driveForward () {
	//code to move the base forward
	//right side of the base
	motor[FrontRightBase] = 100;
	motor[BackRightBase] = 100;
	motor[CenterRightBase] = 100;
	//left side of the base
	motor[FrontLeftBase] = 100;
	motor[BackLeftBase] = 100;
	motor[CenterLeftBase] = 100;
}

void driveBackward () {
	//code to move the base backwards
	//right side of the base
	motor[FrontRightBase] = -100;
	motor[BackRightBase] = -100;
	motor[CenterRightBase] = -100;
	//left side of the base
	motor[FrontLeftBase] = -100;
	motor[BackLeftBase] = -100;
	motor[CenterLeftBase] = -100;
}

void turnLeft () {
	//code to move the base left
	//right side of the base
	motor[FrontRightBase] = -80;
	motor[BackRightBase] = -80;
	motor[CenterRightBase] = -80;
	//left side of the base
	motor[FrontLeftBase] = 80;
	motor[BackLeftBase] = 80;
	motor[CenterLeftBase] = 80;
}

void turnRight () {
	//code to move the base right
	//right side of the base
	motor[FrontRightBase] = 80;
	motor[BackRightBase] = 80;
	motor[CenterRightBase] = 80;
	//left side of the base
	motor[FrontLeftBase] = -80;
	motor[BackLeftBase] = -80;
	motor[CenterLeftBase] = -80;
}

void stopDrive () {
	//code to stop the base
	//right side of the base
	motor[FrontRightBase] = 0;
	motor[BackRightBase] = 0;
	motor[CenterRightBase] = 0;
	//left side of the base
	motor[FrontLeftBase] = 0;
	motor[BackLeftBase] = 0;
	motor[CenterLeftBase] = 0;
}
void flipCaps () {
	motor[CapFlipper] = 127;
}

void noCapFlipping () {
	motor[CapFlipper] = 0;

}

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.

	//slaveMotor makes sure the motors on the back side of the base follows the front side of the base.
	//For example, the back right side of the base will follow the front side fo the base.
	//In this same way, the intake left motor is "slaved" to the intake right motor




	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*
*/
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	//FrontBlue
	wait1Msec(1000);
	resetMotorEncoder(FrontLeftBase);
	while(getMotorEncoder(FrontLeftBase) < 1200)
	{
		driveForward();
		flipCaps();
	}
	wait1Msec(1000);
	turnRight();
	wait1Msec(1000);
	driveForward();
	wait1Msec(1000);

	//BackBlue
	/*
	wait1Msec(1000);
	turnLeft();
	wait1Msec(1000);
	driveForward();
	wait1Msec(1000);
	*/


	//FrontRed
	/*
	wait1Msec(1000);
	turnRight();
	wait1Msec(1000);
	driveForward();
	wait1Msec(1000);
	*/

	//BackRed
	/*
	wait1Msec(1000);
	turnLeft();
	wait1Msec(1000);
	wait1Msec(1000);
	*/

}




/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{

		//motor control for the right side of base
		motor[FrontRightBase] = vexRT[Ch2];
		motor[BackRightBase] = vexRT[Ch2];
		motor[CenterRightBase] = vexRT[Ch2];

		//motor control for the left side of base
		motor[FrontLeftBase] = vexRT[Ch3];
		motor[BackLeftBase] = vexRT[Ch3];
		motor[CenterLeftBase] = vexRT[Ch3];
		if(vexRT[Btn6U] == 1) {
			motor[CapFlipper] = 100;
		}
		else {
			motor[CapFlipper] = 0;
		}
	}
}
