#pragma config(Sensor, I2C_1,  FrontRight,     sensorNone)
#pragma config(Sensor, I2C_2,  BackRight,      sensorNone)
#pragma config(Sensor, I2C_3,  FrontLeft,      sensorNone)
#pragma config(Sensor, I2C_4,  BackLeft,       sensorNone)
#pragma config(Motor,  port1,           CenterRightBase, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           BackRightBase, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           BackLeftBase,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           CenterLeftBase, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           RightLinearPuncher, tmotorNone, openLoop)
#pragma config(Motor,  port7,           Intake,        tmotorNone, openLoop)
#pragma config(Motor,  port8,           Lift,          tmotorNone, openLoop)
#pragma config(Motor,  port9,           FrontLeftBase, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          FrontRightBase, tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void driveForward () {
	//code to move the base forward
	//right side of the base
	motor[FrontRightBase] = 100;
	motor[BackRightBase] = 100;
	motor[CenterRightBase] = 100;
	//left side of the base
	motor[FrontLeftBase] = 100;
	motor[BackLeftBase] = 100;
	motor[CenterLeftBase] = 100;
}

void driveBackward () {
	//code to move the base backwards
	//right side of the base
	motor[FrontRightBase] = -100;
	motor[BackRightBase] = -100;
	motor[CenterRightBase] = -100;
	//left side of the base
	motor[FrontLeftBase] = -100;
	motor[BackLeftBase] = -100;
	motor[CenterLeftBase] = -100;
}

void turnLeft () {
	//code to move the base left
	//right side of the base
	motor[FrontRightBase] = -80;
	motor[BackRightBase] = -80;
	motor[CenterRightBase] = -80;
	//left side of the base
	motor[FrontLeftBase] = 80;
	motor[BackLeftBase] = 80;
	motor[CenterLeftBase] = 80;
}

void turnRight () {
	//code to move the base right
	//right side of the base
	motor[FrontRightBase] = 80;
	motor[BackRightBase] = 80;
	motor[CenterRightBase] = 80;
	//left side of the base
	motor[FrontLeftBase] = -80;
	motor[BackLeftBase] = -80;
	motor[CenterLeftBase] = -80;
}

void stopDrive () {
	//code to stop the base
	//right side of the base
	motor[FrontRightBase] = 0;
	motor[BackRightBase] = 0;
	motor[CenterRightBase] = 0;
	//left side of the base
	motor[FrontLeftBase] = 0;
	motor[BackLeftBase] = 0;
	motor[CenterLeftBase] = 0;
}

void startIntake (){
	//code to turn on the intake
	motor[Intake] = 100;
}

void stopIntake (){
	//code to turn off the intake
	motor[Intake] = 0;
}

void backLinearPuncher () {
	//code to make the linear puncher run back
	motor[RightLinearPuncher] = -100;
	//motor[LeftLinearPuncher] = -100;
}

void stopLinearPuncher () {
	//code to make the linear puncher stop
	motor[RightLinearPuncher] = 0;
	//motor[LeftLinearPuncher] = 0;
}

void startLift () {
	motor[Lift] = 100;
}

void stopLift () {
	motor[Lift] = 0;
}

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.

	//slaveMotor makes sure the motors on the back side of the base follows the front side of the base.
	//For example, the back right side of the base will follow the front side fo the base.
	//In this same way, the intake left motor is "slaved" to the intake right motor




	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	wait1Msec(1000);
	SensorValue[FrontLeft] = 0;
	SensorValue[BackLeft]= 0;
	SensorValue[FrontRight]= 0;
	SensorValue[BackRight] = 0;
	if (SensorValue(FrontLeft) < 1800){
		driveForward();
		wait1Msec(2000);
		stopDrive();
	}
	wait1Msec(2000);
	turnRight();
	wait1Msec(2000);
	driveForward();
	wait1Msec(2000);
	stopDrive();
	wait1Msec(2000);
	/*turnLeft();
	wait1Msec(2000);
	stopDrive();
	wait1Msec(5000);
	driveBackward();
	wait1Msec(3000);*/
	turnLeft();
	wait1Msec(2000);
	driveForward();
	wait1Msec(2000);
	/*startIntake();
	wait1Msec(2000);
	stopIntake();
	wait1Msec(2000);
	backLinearPuncher();
	wait1Msec(2000);
	stopLinearPuncher();
	wait1Msec(2000);*/
}




/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{

		//motor control for the right side of base
		motor[FrontRightBase] = vexRT[Ch2];
		motor[BackRightBase] = vexRT[Ch2];
		motor[CenterRightBase] = vexRT[Ch2];

		//motor control for the left side of base
		motor[FrontLeftBase] = vexRT[Ch3];
		motor[BackLeftBase] = vexRT[Ch3];
		motor[CenterLeftBase] = vexRT[Ch3];
		//motor control for the linear puncher
		if (vexRT[Btn6UXmtr2] == 1) {
			backLinearPuncher();
			wait1Msec(1000);
		}
		else {
			stopLinearPuncher();
		}
		//motor control for the lift
		if (vexRT[Btn5U] == 1) {
			motor[Lift] = 100;
		}
		else if (vexRT[Btn5UXmtr2] == 0 && vexRT[Btn5DXmtr2] == 1) {
			motor[Lift] = -100;
		}
		else {
			motor[Lift] = 0;
		}
	}
}
