#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLight,      sensorLineFollower)
#pragma config(Sensor, in2,    rightLight,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  sonar,          sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  leftRearEnc,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftFrontEnc,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  rightFrontEnc,  sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  rightRearEnc,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           clawMotor,     	tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightFrontMotor, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           leftFrontMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port4,           rightRear2,    tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port5,           leftRear2,     tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port6,           leftMobileMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           leftLiftMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightLiftMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           rightMobileMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void mgLiftDown(int speed, int time)
{
	motor[rightMobileMotor] = speed;
	motor[leftMobileMotor] = speed;
	wait1Msec(time);
}
void stopmgLift()
{
	motor[rightMobileMotor] = 0;
	motor[leftMobileMotor] = 0;
}
void mgLiftUp(int speed, int time)
{
	motor[rightMobileMotor] = -speed;
	motor[leftMobileMotor] = -speed;
	wait1Msec(time);
}
void driveForward(int leftSpeed, int rightSpeed)
{
	motor[rightRear2] = rightSpeed;
	motor[rightFrontMotor] = rightSpeed;
	motor[leftFrontMotor] = leftSpeed;
	motor[leftRear2] = leftSpeed;
	//wait1Msec(time);
}
void driveBackward(int leftSpeed, int rightSpeed)
{
	motor[rightRear2] = -rightSpeed;
	motor[rightFrontMotor] = -rightSpeed;
	motor[leftFrontMotor] = -leftSpeed;
	motor[leftRear2] = -leftSpeed;
	//wait1Msec(time);
}
void stopDrive()
{
	motor[rightRear2] = 0;
	motor[rightFrontMotor] = 0;
	motor[leftFrontMotor] = 0;
	motor[leftRear2] = 0;
}
void turnLeft(int speed)
{
	motor[rightRear2] = speed;
	motor[rightFrontMotor] = speed;
	motor[leftFrontMotor] = -speed;
	motor[leftRear2] = -speed;

}
void turnRight(int speed, int time)
{
	motor[rightRear2] = -speed;
	motor[rightFrontMotor] = -speed;
	motor[leftFrontMotor] = speed;
	motor[leftRear2] = speed;
	wait1Msec(time);
}
void turnRight2(int speed)
{
	motor[rightRear2] = -speed;
	motor[rightFrontMotor] = -speed;
	motor[leftFrontMotor] = speed;
	motor[leftRear2] = speed;

}
void openClaw(int speed, int time)
{
	motor[clawMotor] = speed;
	wait1Msec(time);
}
void closeClaw(int speed, int time)
{
	motor[clawMotor] = -speed;
	wait1Msec(time);
}
void stopClaw()
{
	motor[clawMotor] = 0;
}
void clawLiftUp(int speed, int time)
{
	motor[leftLiftMotor]	= speed;
	motor[rightLiftMotor] = speed;
	wait1Msec(time);
}
void clawLiftDown(int speed, int time)
{
	motor[leftLiftMotor] = -speed;
	motor[rightLiftMotor] = -speed;
	wait1Msec(time);
}
void stopLift()
{
	motor[leftLiftMotor] = 0;
	motor[rightLiftMotor] = 0;
}

const float fullCycle = 392;
const float fullSpeed = 127;
int motorValue = 110;
task main()
{
	mgLiftDown(120,1250); //by "mgLift" i mean the stuff that lifts the mobilegoal *~*
	stopmgLift();

	SensorValue[leftFrontEnc] = 0;
	SensorValue[rightFrontEnc]= 0;



while(abs(SensorValue[leftFrontEnc]) < 4*fullCycle)
{
	if(SensorValue [leftFrontEnc]<SensorValue[rightFrontEnc])
	{
			driveBackward(motorValue+10, motorValue);
			}
	if(SensorValue [rightFrontEnc]<SensorValue[leftFrontEnc])
	{
		driveBackward(motorValue, motorValue+10);
			}
	if(SensorValue [leftFrontEnc]== SensorValue[rightFrontEnc])
	{
		driveBackward(motorValue, motorValue);
			}
  }

	stopDrive();
	wait1Msec(200);

	mgLiftUp(120, 1500);//need to make sure the time (minimized)
	stopmgLift();

		SensorValue[leftFrontEnc] = 0;
	SensorValue[rightFrontEnc]= 0;
	while(abs(SensorValue[leftFrontEnc]) < 1.5*fullCycle)
	{
		turnRight2(110);
	}
	stopDrive();
	wait1Msec(500);


		SensorValue[leftFrontEnc] = 0;
	SensorValue[rightFrontEnc]= 0;


while(abs(SensorValue[leftFrontEnc]) < 4.5*fullCycle)
{
	if(SensorValue [leftFrontEnc]<SensorValue[rightFrontEnc])
	{
			driveBackward(motorValue+10, motorValue);
			}
	if(SensorValue [rightFrontEnc]<SensorValue[leftFrontEnc])
	{
		driveBackward(motorValue, motorValue+10);
			}
	if(SensorValue [leftFrontEnc]== SensorValue[rightFrontEnc])
	{
		driveBackward(motorValue, motorValue);
			}
  }

	stopDrive();
	wait1Msec(200);

	mgLiftDown(100, 1250);
	stopmgLift();
	wait1Msec(200);
	mgLiftUp(100, 1000);

	SensorValue[leftFrontEnc] = 0;
	SensorValue[rightFrontEnc]= 0;



while(abs(SensorValue[leftFrontEnc]) < 1*fullCycle)
{
	if(SensorValue [leftFrontEnc]<SensorValue[rightFrontEnc])
	{
			driveBackward(motorValue+10, motorValue);
			}
	if(SensorValue [rightFrontEnc]<SensorValue[leftFrontEnc])
	{
		driveBackward(motorValue, motorValue+10);
			}
	if(SensorValue [leftFrontEnc]== SensorValue[rightFrontEnc])
	{
		driveBackward(motorValue, motorValue);
			}
  }

	//liftUp(100,1500); //by "mgLift" i mean the stuff that lifts the mobilegoal *~*
	//stopLift();
	//driveForward(100,100);
	//wait1Msec(500); //???
	//liftDown(100,1500);//need to make sure the time (minimized)
	//stopLift();

	//then we go back





}
