#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_2,  leftFrontEnc,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_1,  leftRearEnc,    sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  rightFrontEnc,  sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  rightRearEnc,   sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           clawMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftRearMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           leftFrontMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
#pragma config(Motor,  port4,           rightRearMotor, tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port5,           rightFrontMotor, tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port7,           leftLiftMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           rightLiftMotor, tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

#pragma autonomousDuration(0)
#pragma userControlDuration(60)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

//#define recordIndefinitely
//#include "autonRecorder.c"
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/


int motorValue=127;

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

void liftUp(int speed, int time)
{
	motor[rightLiftMotor] = speed;
	motor[leftLiftMotor] = speed;
	wait1Msec(time);
}
void stopLift()
{
	motor[rightLiftMotor] = 0;
	motor[leftLiftMotor] = 0;
}
void liftDown(int speed, int time)
{
	motor[rightLiftMotor] = -speed;
	motor[leftLiftMotor] = -speed;
	wait1Msec(time);
}
void driveForward(int leftSpeed, int rightSpeed)
{
	motor[rightRearMotor] = rightSpeed;
	motor[rightFrontMotor] = rightSpeed;
	motor[leftFrontMotor] = leftSpeed;
	motor[leftRearMotor] = leftSpeed;
	//wait1Msec(time);
}
void driveBackward(int leftSpeed, int rightSpeed)
{
	motor[rightRearMotor] = -rightSpeed;
	motor[rightFrontMotor] = -rightSpeed;
	motor[leftFrontMotor] = -leftSpeed;
	motor[leftRearMotor] = -leftSpeed;
	//wait1Msec(time);
}
void stopDrive()
{
	motor[rightRearMotor] = 0;
	motor[rightFrontMotor] = 0;
	motor[leftFrontMotor] = 0;
	motor[leftRearMotor] = 0;
}
void turnLeft(int speed, int time)
{
	motor[rightRearMotor] = speed;
	motor[rightFrontMotor] = speed;
	motor[leftFrontMotor] = -speed;
	motor[leftRearMotor] = -speed;
	wait1Msec(time);
}
void turnRight(int speed, int time)
{
	motor[rightRearMotor] = -speed;
	motor[rightFrontMotor] = -speed;
	motor[leftFrontMotor] = speed;
	motor[leftRearMotor] = speed;
	wait1Msec(time);
}
void openClaw(int speed, int time)
{
	motor[clawMotor] = speed;
	wait1Msec(time);
}
void closeClaw(int speed, int time)
{
	motor[clawMotor] = -speed;
	wait1Msec(time);
}
void stopClaw()
{
	motor[clawMotor] = 0;
}

const float fullCycle = 392;


//Autonomous

task autonomous()
{
	liftUp(100,1500); //by "mgLift" i mean the stuff that lifts the mobilegoal *~*
	stopLift();

	SensorValue[leftFrontEnc] = 0;
	SensorValue[rightFrontEnc]= 0;

	//closeClaw(60,2000);
	//liftUp();
	//wait1Msec(1500);
	//stopLift();

	//TODO: LINE TRACKER

while(SensorValue[leftFrontEnc] < 2.8*fullCycle){

		if(SensorValue [leftFrontEnc]<SensorValue[rightFrontEnc])
		{
			driveForward(-motorValue, -motorValue+20);
			//motor[leftFrontMotor] = -motorValue;
			//motor[leftRearMotor]= -motorValue;
			//motor[rightFrontMotor]= -motorValue+20;
			//motor[rightRearMotor]= -motorValue+20;
			}
		else if(SensorValue [rightFrontEnc]<SensorValue[leftFrontEnc])
		{
			driveForward(-motorValue+20, -motorValue);
			//motor[leftFrontMotor] = -motorValue+20;
			//motor[leftRearMotor]= -motorValue+20;
			//motor[rightFrontMotor]= -motorValue;
			//motor[rightRearMotor]= -motorValue;
			}
		else if(SensorValue [leftFrontEnc]== SensorValue[rightFrontEnc])
		{
			driveForward(-motorValue, -motorValue);
			//motor[leftFrontMotor] = -motorValue;
			//motor[leftRearMotor]= -motorValue;
			//motor[rightFrontMotor]= -motorValue;
			//motor[rightRearMotor]= -motorValue;
			}
  	}

	stopDrive();
	wait1Msec(200);

	liftDown(100,1500);//need to make sure the time (minimized)
	stopLift();

	//moveBackward

	//liftUp(100,1500); //by "mgLift" i mean the stuff that lifts the mobilegoal *~*
	//stopLift();
	//driveForward(100,100);
	//wait1Msec(500); //???
	//liftDown(100,1500);//need to make sure the time (minimized)
	//stopLift();

	//then we go back

	while(SensorValue[leftLight] < 1430){
			driveForward(100,100);
	}
	driveForward(100,100); //?
	//setmotorencoder

	while(SensorValue[leftLight] < 1430 || SensorValue[rightLight] < 1430 ){
		if(SensorValue[leftLight] < 1430 && SensorValue[rightLight] >= 1430){
				motor[rightRearMotor] = 0;
				motor[rightFrontMotor] = 0;
				//motor[rearLeftMotor] = 100;
				//motor[frontLeftMotor] = 100;
		}else if(SensorValue[rightLight] < 1430 && SensorValue[leftLight] >= 1430){
				motor[leftRearMotor] = 0;
				motor[leftFrontMotor] = 0;
				//motor[rearRightMotor] = 100;
				//motor[frontRightMotor] = 100;
		}	else if(SensorValue[leftLight] < 1430 && SensorValue[rightLight] < 1430){
		//180degree
		turnRight(100,1000); //need to make sure the time
		}
	}

	//robot's carrying the mobile goal with its back to the white light and the ten points area
	//move backward

	driveBackward(100);
	wait1Msec(1000); //need to make sure the time, or use motorencoder

	liftDown(100,1500); //by "mgLift" i mean the stuff that lifts the mobilegoal *~*
	stopLift();
	wait1Msec(500);//maybe longer
	//liftUp(100,1500); //need to make sure the time (minimized)
	//stopLift();

	driveForward(127);
	wait1Msec(1000); //?
	stopDrive();

	}


task usercontrol()
{
  // User control code here, inside the loop
//startTask(autonRecorder);
while (true)
{
	//Drive Controls (main controller: left motors on left joystick; right motors on right joystick)
 	motor[leftFrontMotor] = vexRT[Ch3];
 	motor[leftRearMotor] = vexRT[Ch3];
 	motor[rightFrontMotor] = vexRT[Ch2];
 	motor[rightRearMotor] = vexRT[Ch2];

	//Claw Controls (secondary controller: button 6U opens claw and 6D closes claw)
	if (vexRT[Btn6UXmtr2] == 1 && vexRT[Btn6DXmtr2] == 0)
	{
		motor[clawMotor] = 127;
	}
	else if (vexRT[Btn6DXmtr2] == 1 && vexRT[Btn6UXmtr2] == 0)
	{
		motor[clawMotor] = -127;
	}
	else
	{
		motor[clawMotor] = 0;
	}

	//Lift Controls (secondary controller; right joystick)
	motor[leftLiftMotor] = vexRT[Ch2Xmtr2];
	motor[rightLiftMotor] = vexRT[Ch2Xmtr2];
	}
}
